name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --check .

      - name: Run Jest tests
        run: npm test

      - name: Build frontend
        run: npm run build
        env:
          REACT_APP_CHAT_ENGINE_PROJECT_ID: ${{ secrets.REACT_APP_CHAT_ENGINE_PROJECT_ID }}

      - name: Deploy to Render (Staging)
        if: github.ref == 'refs/heads/develop'
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_STAGING_HOOK }}

      - name: Deploy to Render (Production)
        if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_PRODUCTION_HOOK }}

  build-and-test-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --check .

      - name: Run Jest tests
        run: npm test

      - name: Deploy to Render (Staging)
        if: github.ref == 'refs/heads/develop'
        run: curl -X POST ${{ secrets.RENDER_BACKEND_STAGING_HOOK }}

      - name: Deploy to Render (Production)
        if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
        run: curl -X POST ${{ secrets.RENDER_BACKEND_PRODUCTION_HOOK }}
