name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on merge to main (production)
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --check .

      - name: Run Jest tests
        run: npm test

      - name: Build frontend
        run: npm run build
        env:
          REACT_APP_CHAT_ENGINE_PROJECT_ID: ${{ secrets.REACT_APP_CHAT_ENGINE_PROJECT_ID }}

  build-and-test-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --check .

      - name: Run Jest tests
        run: npm test

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-and-test-frontend, build-and-test-backend]

    steps:
      - name: Notify Render to Deploy Frontend
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_PRODUCTION_HOOK }}

      - name: Notify Render to Deploy Backend
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_PRODUCTION_HOOK }}

  monitoring:
    name: Set up Monitoring (Prometheus and Grafana)
    runs-on: ubuntu-latest
    needs: deploy-to-production  # This ensures monitoring runs after deployment

    steps:
      - name: Configure Prometheus
        run: |
          # Commands to configure Prometheus on your Render instance
          echo "Setting up Prometheus for monitoring"

      - name: Configure Grafana
        run: |
          # Commands to configure Grafana on your Render instance
          echo "Setting up Grafana for monitoring"
